name: CI Build Spring Boot App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Copy Jar
    runs-on: self-hosted

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Show workspace
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          ls -la

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          
      # Cấp quyền thực thi cho file mvn
      - name: Ensure mvnw executable
        run: |
          cd ${{ github.workspace }}
          chmod +x mvnw
           
      # Build NGAY TRONG workspace của runner
      - name: Build with Maven
        working-directory: ${{ github.workspace }}
        run: ./mvnw -B clean package -DskipTests

      - name: List built artifacts
        run: ls -lh ${{ github.workspace }}/target

      # Copy .jar sang chỗ bạn muốn chạy app
#      - name: Copy jar to run directory
#        run: |
#          cp ${{ github.workspace }}/target/*.jar \
#             /home/nvkhoacoder/product_project/product_source/product-management.jar
#          chown nvkhoacoder:nvkhoacoder /home/nvkhoacoder/product_project/product_source/product-management.jar
      - name: Copy jar to run directory
        run: |
          mkdir -p /home/nvkhoacoder/product_project/product_source
          cp ${{ github.workspace }}/target/*.jar \
             /home/nvkhoacoder/product_project/product_source/product-management.jar
          chown -R nvkhoacoder:nvkhoacoder /home/nvkhoacoder/product_project/product_source


  deploy:
    name: Deploy Project
    runs-on: self-hosted
    needs: build

    steps:
      - name: Restart product-app service
        run: |
          sudo systemctl restart product-app
          sudo systemctl status product-app --no-pager
#          sudo systemctl daemon-reload